class Auth0Error(Exception):
    pass
